[tool.poetry]
name = "poetry-demo"
version = "0.1.0"
description = ""
authors = ["Igor <GIV_84@mail.ru>"]
readme = "README.md"
packages = [{include = "poetry_demo"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
